services:
- type: web
  name: hasura
  env: docker
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_METADATA_DATABASE_URL
    fromDatabase:
      name: hasura
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: PORT
    value: 10000
# Uncomment to automatically generate an admin secret
# for your Hasura instance. The value is visible under
# Environment on the Render dashboard.
#  - key: HASURA_GRAPHQL_ADMIN_SECRET
#    generateValue: true
databases:
- name: hasura
